name: flutter_open_scad
description: "Create OpenSCAD models in a GUI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  backstreets_widgets: ^0.35.1
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  recase: ^4.1.0
  riverpod_annotation: ^3.0.0-dev.17
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.6.0
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter:
  uses-material-design: true
